### ISSUE TITLE
trouble connecting to the bno055

### ISSUE THREAD

**Issue by torn8to** [flynneva/bno055#46]
plugged into a bno055 hitlego cp2104 into USB to uart converter into the USB port into a USB device.  

/dev/ttyUSB0 does exist but i needed to delete brltty
![IMG-3807](https://user-images.githubusercontent.com/61364765/183494759-29d8100f-181a-4dc6-bf05-c5b8d3c2a9db.JPG)
![IMG_3806](https://user-images.githubusercontent.com/61364765/183494761-ad301a0f-da14-460d-85bc-c8d15217dbd6.jpg)

I get the error message on both that the device is not connected even when 5volts are going through the device it is also cool at this time with about 1.5v being dropped after passing through the device.

**Comment by flynneva** [comment]
hey @torn8to! sorry you are having trouble (so did I when I first tried connecting to a bno055).

Have you double checked that you have selected UART mode for the bno055? See  [this section](https://github.com/flynneva/bno055#selecting-connection-type) of the README.

Also, just to be sure double check [the pins are connected properly](https://github.com/flynneva/bno055#selecting-connection-type) and are making a good connection.

As a final recommendation: do you have a second bno055 to test? I have fried one before during initial setup (connecting wrong pins to each other) and it never turned on after that.  You may have a dead bno055 in that case and need to get a replacement.

**Comment by flynneva** [comment]
Closing due to in-activity. Feel free to reopen if this is still an issue for you
