### ISSUE TITLE
operation_mode is hard-coded to NDOF

### ISSUE THREAD

**Issue by sjev** [flynneva/bno055#48]
First of all, many thanks for this repo! 

I was trying to set the sensor into `IMU` mode with the config file, but it was still functioning in absolute mode.
Then I've taken a look at the [code](https://github.com/flynneva/bno055/blob/HEAD/bno055/sensor/SensorService.py#L133) and it turns out that  setting `operation_mode` is hard-coded to NDOF.

``` python
# Set Device to NDOF mode
# data fusion for gyroscope, acceleration sensor and magnetometer enabled
# absolute orientation
if not (self.con.transmit(registers.BNO055_OPR_MODE_ADDR, 1, bytes([registers.OPERATION_MODE_NDOF]))):
        self.node.get_logger().warn('Unable to set IMU operation mode into operation mode.')
```

P.S. I could change it myself and send a PR, just let me know.

**Comment by flynneva** [comment]
@
