### ISSUE TITLE
BNO055 somtimes sends BUS_OVER_RUN_ERROR (0x07) over UART

### ISSUE THREAD

**Issue by whatis777** [flynneva/bno055#5]
BNO055 sends back BUS_OVER_RUN_ERROR (0x07) over UART.

This seems to be a known issue when performing regular sensor data queries using UART: https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BNO55-0x07-error-UART/td-p/14765

Therefor this project is currently logging a regular warning regarding this issue:
`[WARN] [1610880440.010281061] [bno055]: Receiving sensor data failed with TransmissionException:"READ-request failed with error code 0x7"`

If a project does not depend on a strict cyclic sensor data update, it can just ignore the warning. The data will be there for the next query cycle.

As the severity seems to be very low, should we disable the warning logging to prevent console / log pollution?

**Comment by flynneva** [comment]
hi @whatis777, good find.

from the link you shared it looks like the recommended course of action is to just resend the read command if connected via UART. within our code I think we could do a similar filter if connected via UART, ignore this 0x07 error and resend a read request.

what do you think?

**Comment by whatis777** [comment]
I think we could even stick to the regular data request cycle: as there is no realtime guarantee (due to the system design and underlying OS), and as the data query frequency is quite high it shouldn't be a problem if one query cycle does not produce IMU data... the next regular cycle will provide data again a few milliseconds later

**Comment by flynneva** [comment]
@whatis777 finally getting some more bno055's in the mail today, so hopefully should be able to test this some more 😄
