### ISSUE TITLE
call calibration 

### ISSUE THREAD

**Issue by UltraHertzz** [flynneva/bno055#66]
Hello! I have tried to calibrate my bno055 device, but the system is always wait for service, also I didn't see the srv folder in the repo, is that in another package? Thx.

**Comment by flynneva** [comment]
@UltraHertzz the calibration service just reads the calibration values from the device, I don't think it actually does the calibration for you.

We could add that as a feature here, but probably would need someone to add it 😅

The service today just uses the example service Trigger, not located in this package but it's listed as a dependency.

**Comment by UltraHertzz** [comment]
ok got it.
