### ISSUE TITLE
Interest in tagging a new release?

### ISSUE THREAD

**Issue by traversaro** [flynneva/bno055#68]
Thanks a lot @flynneva for working on this repo! As it passed some time since the last release (0.4.1) and some fixes (such as https://github.com/flynneva/bno055/pull/59) are not yet released, are you interested in making a new release, also in view of ROS 2 Jazzy? 

Thanks a lot in advance!

**Comment by flynneva** [comment]
@traversaro sure! I'll cut a new one this week 👍

**Comment by traversaro** [comment]
> @traversaro sure! I'll cut a new one this week 👍

Thanks!

**Comment by flynneva** [comment]
@traversaro I've tagged and opened up rosdistro PRs for all active ROS 2 distros (here is the rolling PR: https://github.com/ros/rosdistro/pull/39928).

Now we wait for them to get reveiwed / merged and then for a patch release for each distro.

Going to close this issue as complete 👍🏼

**Comment by traversaro** [comment]
Thanks a lot!
